// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Ondato.DB;

namespace Ondato.DB.Migrations
{
    [DbContext(typeof(OndatoContext))]
    [Migration("20210211074625_InitDB")]
    partial class InitDB
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .UseIdentityColumns()
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.1");

            modelBuilder.Entity("Ondato.DB.Models.DictionaryKey", b =>
                {
                    b.Property<string>("Key")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("CreatedDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("getdate()");

                    b.Property<DateTime>("UpdatedDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("getdate()");

                    b.HasKey("Key");

                    b.ToTable("DictionaryKeys");
                });

            modelBuilder.Entity("Ondato.DB.Models.DictionaryValue", b =>
                {
                    b.Property<int>("DictionaryValueId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<byte[]>("Value")
                        .IsRequired()
                        .HasColumnType("varbinary(max)");

                    b.HasKey("DictionaryValueId");

                    b.HasIndex("Key");

                    b.ToTable("DictionaryValues");
                });

            modelBuilder.Entity("Ondato.DB.Models.DictionaryValue", b =>
                {
                    b.HasOne("Ondato.DB.Models.DictionaryKey", "DictionaryKey")
                        .WithMany("DictionaryValues")
                        .HasForeignKey("Key")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DictionaryKey");
                });

            modelBuilder.Entity("Ondato.DB.Models.DictionaryKey", b =>
                {
                    b.Navigation("DictionaryValues");
                });
#pragma warning restore 612, 618
        }
    }
}
